version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: company
    ports:
      - "3306:3306"
    volumes:
      # Mount the SQL files to be executed when container starts
      - ./dump-company-202509162226.sql:/docker-entrypoint-initdb.d/01-dump-company.sql
      # Mount a volume for persistent data storage
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-pyour_password",
        ]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
    driver: local
